#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install
ynh_hide_warnings corepack enable && corepack prepare pnpm@latest --activate

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="server.env" --destination="$install_dir/apps/server/.env"
ynh_config_add --template="web.env" --destination="$install_dir/apps/web/.env"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
ynh_config_add_systemd --service=$app-web --template=web.service

yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"
yunohost service add "$app-web" --description="A short description of the app" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir/apps/server
    ynh_hide_warnings ynh_exec_as_app pnpm install
    ynh_hide_warnings ynh_exec_as_app pnpm dlx prisma generate
    ynh_hide_warnings ynh_exec_as_app pnpm dlx prisma migrate deploy
    ynh_hide_warnings ynh_exec_as_app pnpm db:seed
    ynh_hide_warnings ynh_exec_as_app pnpm run build
popd

pushd $install_dir/apps/web
    ynh_hide_warnings ynh_exec_as_app pnpm install
    ynh_hide_warnings ynh_exec_as_app pnpm run build
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"
ynh_systemctl --service="$app-web" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
